when i use below error not thrown
why?
def get_ta_refund_details(booking):
    obj = TaRefundAccountDetails.objects.filter(tm_booking_id=booking.tm_booking_id).first()
    refunds = TaRefundAccountDetailsSerializer(obj).data
    return refunds
